### PR TITLE
Revert "Make it pythonic"

### PR DESCRIPTION
**Pull request by sdushantha**
Reverts sdushantha/neofetch#1

REASON FOR REVERTING
1. There is no color on the Apple logo and the text.
2. The process is slow. Each lines prints slowly which gives a bad effect.

### CODE REVIEW

**Comment by SVilgelm** [comment]
Are you sure you used correct version? It works on my laptop fine

**Comment by SVilgelm** [comment]
https://www.dropbox.com/s/m135kq9czzd3f9t/Screen%20Shot%202017-12-20%20at%2010.04.25%20AM.png

**Comment by SVilgelm** [comment]
1. Execution of your version:
`python -m timeit -n 1 -r 100 -s 'import os' 'os.system("./neofetch")'`
1 loops, best of 100: 1.04 sec per loop

2. Execution of my version:
`python -m timeit -n 1 -r 100 -s 'import os' 'os.system("neofetch")'`
1 loops, best of 100: 888 msec per loop

**Comment by sdushantha** [comment]
This is wha I get

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/neofetch", line 11, in <module>
    load_entry_point('neofetch==1.0', 'console_scripts', 'neofetch')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'neofetch.neofetch'; 'neofetch' is not a package

**Comment by SVilgelm** [comment]
How did you install it?

**Comment by SVilgelm** [comment]
try this: `pip install --user git+https://github.com/svilgelm/neofetch.git@make_it_pythonic`

**Comment by SVilgelm** [comment]
or `pip install git+https://github.com/svilgelm/neofetch.git@make_it_pythonic`

**Comment by sdushantha** [comment]
tried the first one but when i ran the neofetch command, i got command not found error. Then i tried the second command but then i still got the same error as I said before

**Pull request merged**
